export const userData = [
  {
    id: 1,
    investorName: 'Robin',
    receiverName: 'PixelWizard',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 2,
    investorName: 'EchoNomad',
    receiverName: 'MysticShadow',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },

  {
    id: 3,
    investorName: 'QuantumWave',
    receiverName: 'PixelWizard',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 4,
    investorName: 'Robin',
    receiverName: 'SilverFalcon',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 5,
    investorName: 'PhoenixRise',
    receiverName: 'PixelWizard',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 6,
    investorName: 'Robin',
    receiverName: 'ShadowSerpent',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 7,
    investorName: 'Robin',
    receiverName: 'SpectralFlame',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 8,
    investorName: 'MidnightGlider',
    receiverName: 'PixelWizard',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 9,
    investorName: 'Robin',
    receiverName: 'MidnightGlider',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 10,
    investorName: 'NovaSpecter',
    receiverName: 'PixelWizard',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },

  {
    id: 11,
    investorName: 'Robin',
    receiverName: 'NovaSpecter',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 12,
    investorName: 'TitanVortex',
    receiverName: 'PixelWizard',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 13,
    investorName: 'Robin',
    receiverName: 'TitanVortex',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 14,
    investorName: 'Robin',
    receiverName: 'ZenithVoyager',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
  {
    id: 15,
    investorName: 'ZenithVoyager',
    receiverName: 'PixelWizard',
    investAmount: 9,
    receiveAmount: 1,
    timeStamp: 'a few second ago',
  },
];
